// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGLIdfI5B_627tUrfjId2UftoKopGeJHY',
    appId: '1:385046326132:web:defc3d3700fab183821a21',
    messagingSenderId: '385046326132',
    projectId: 'preciouspeople-56f0c',
    authDomain: 'preciouspeople-56f0c.firebaseapp.com',
    storageBucket: 'preciouspeople-56f0c.appspot.com',
    measurementId: 'G-1ZEQSPV9S0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFt0Iv9Rz_2XXXr7WCNIYTYpFJEXSnTs0',
    appId: '1:385046326132:android:10b084c4b7d625eb821a21',
    messagingSenderId: '385046326132',
    projectId: 'preciouspeople-56f0c',
    storageBucket: 'preciouspeople-56f0c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdHv1q4VM06VIXdDo5349UFvqmjkKbXY0',
    appId: '1:385046326132:ios:0021761d498be1c9821a21',
    messagingSenderId: '385046326132',
    projectId: 'preciouspeople-56f0c',
    storageBucket: 'preciouspeople-56f0c.appspot.com',
    iosBundleId: 'com.nice.preciousPeople',
  );
}
